---
- name: Pull Docker Image of movie app
  hosts: localhost
  connection: local
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Pull image
      docker_image:
        name: neogenkai/moviesapp:latest
        source: pull
    #    - name: Start docker service
    #      service:
    #        name: docker
    #        state: started
    - name: Running container
      shell: docker-compose -f docker-compose.yml up